### ISSUE TITLE
Exception with kafka 0.8.2.0

### ISSUE THREAD

**Issue by dinoshauer** [airbnb/kafka-statsd-metrics2#2]
Hey I'm getting this exception using kafka 0.8.2.0, are you still supporting this project?

```
[2015-03-16 10:41:03,311] ERROR Error printing regular metrics: (com.airbnb.metrics.StatsDReporter)
java.util.NoSuchElementException
    at java.util.concurrent.ConcurrentSkipListMap$Iter.advance(ConcurrentSkipListMap.java:2224)
    at java.util.concurrent.ConcurrentSkipListMap$ValueIterator.next(ConcurrentSkipListMap.java:2253)
    at scala.collection.JavaConversions$JIteratorWrapper.next(JavaConversions.scala:575)
    at scala.collection.IterableLike$class.head(IterableLike.scala:90)
    at scala.collection.JavaConversions$JCollectionWrapper.head(JavaConversions.scala:592)
    at kafka.log.Log.logStartOffset(Log.scala:502)
    at kafka.log.Log$$anon$2.value(Log.scala:86)
    at kafka.log.Log$$anon$2.value(Log.scala:85)
    at com.airbnb.metrics.StatsDReporter.processGauge(StatsDReporter.java:198)
    at com.airbnb.metrics.StatsDReporter.processGauge(StatsDReporter.java:51)
    at com.yammer.metrics.core.Gauge.processWith(Gauge.java:28)
    at com.airbnb.metrics.StatsDReporter.printRegularMetrics(StatsDReporter.java:157)
    at com.airbnb.metrics.StatsDReporter.run(StatsDReporter.java:104)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by alexism** [comment]
Hi @Dinoshauer ,

since `0.4.0`, kafka `0.8.2` is supported. We successfully use it in production.
wanna upgrade and try again?

**Comment by dinoshauer** [comment]
Wonderful! It will have to wait a while though, for some reason it's not that easy for our cluster to survive reboots with live consumers and producers without having a long downtime :\
